# Generated by Django 5.2.6 on 2025-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_17',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_18',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_19',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_20',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_21',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_22',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_23',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_24',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_25',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_26',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_27',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_28',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_29',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_30',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_31',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_33',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_34',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_35',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_36',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_37',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_38',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_39',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_40',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_41',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_42',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_43',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_44',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_45',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_46',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_47',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='unnamed_48',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='current_company',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='designation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='institue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='skills',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
