# Generated by Django 5.2.6 on 2025-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0002_exceldata_unnamed_16_exceldata_unnamed_17_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_16',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_17',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_18',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_19',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_20',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_21',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_22',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_23',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_24',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_25',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_26',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_27',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_28',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_29',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_30',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_31',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_32',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_33',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_34',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_35',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_36',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_37',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_38',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_39',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_40',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_41',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_42',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_43',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_44',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_45',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_46',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_47',
        ),
        migrations.RemoveField(
            model_name='exceldata',
            name='unnamed_48',
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='current_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='institue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
