# Generated by Django 5.2.6 on 2025-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_to_db', '0003_remove_exceldata_unnamed_16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
